# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e27c173cdfbc09f1f55a97db14e397da363b765f5003676e5673e9bd5bddabef3b69969d2161de1d81407e918c5941ed50fd6db70173c78395c1adb1a5ee898c

test:
  secret_key_base: 7abac402ec536d528688e3137b44753c1aa55b9208479ba509cd1780b1f72c2de43ca8d0f5cf4ae9a88c673c0e74077e67476e2a5fa57d601650421f3d460f79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
